### PR TITLE
MixBytes Submission for CryptoLife

### PR DESCRIPTION
**Pull request by Eenae**
Community curated DApp registry
======

Economic incentives of TCR for curators, IFPS for total decentralization, new JSON Schema standard to describe DApps

https://devpost.com/software/community-curated-dapp-registry

### CODE REVIEW

**Comment by andytudhope** [comment]
Hey @Eenae - please will you rebase this PR against the `mixbytes_dapp-tcr` branch in this repo?

**Comment by Eenae** [comment]
@andytudhope I don't see this branch in github.com/status-im/CryptoLife, could you please create it?

**Comment by andytudhope** [comment]
Done, sorry about that... Thanks again for participating, was so awesome to have you at #CryptoLife

**Comment by Eenae** [comment]
done

**Pull request merged**
