### PR TITLE
Team RicLoo - meeseeks.app

### PR DESCRIPTION
**Pull request by ricmoo**
Initial submission for Status cryptolife Hackathon...

May grab a few winks of sleep and dream of electric sheep.

### CODE REVIEW

**Comment by andytudhope** [comment]
Hey @ricmoo - please can you rebase this against the new `ricloo` branch in this repo so we can avoid merge conflicts?

**Comment by ricmoo** [comment]
@andytudhope  I don't usually use rebasing... Any hints? :)

**Comment by ligi** [comment]
@ricmoo he actually does not want us to rebase but change the base. To do this you click edit on the top right and then use the drop down right to "into:" from master to ricloo

**Comment by ricmoo** [comment]
Ohhh! That makes sense. :)

Done! ;)

**Pull request merged**
